### ISSUE TITLE
Interact with real time environment

### ISSUE THREAD

**Issue by Kenisy** [opherlieber/rltime#1]
Hi, may I ask how to use this library for real time environment instead of gym environments ?

**Comment by opherlieber** [comment]
Hey, for real-time environments, you should still wrap them with the standard gym interface, and you can then use the [AsyncActor](https://github.com/opherlieber/rltime/blob/master/rltime/acting/async_actor.py) class instead of the default actor class which will interact with your environment continuously, and not stall the environment during training. 

If you have many environment instances and/or want to run them remotely you can also look at the option of running them in a [Ray acting pool](https://github.com/opherlieber/rltime/blob/master/docs/distributed_acting.md).
